npmRegistryServer: "https://registry.npmjs.org" # Set custom registry (equivalent to npm's registry)
npmAuditLevel: "moderate" # Exit only on moderate or higher vulnerabilities
enableStrictSsl: false # Disable SSL certificate checks (similar to npm's strict-ssl=false)
cacheFolder: "~/.yarn" # Cache directory override
npmDisableAudit: true # Disable audit entirely:
npmAuditIgnoreAdvisories: # Control audit output verbosity
    - 1234567
    - 7654321
